// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d8bdbf6e-0602-43aa-b637-94d5135044fc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ERDtrWWNL",
    "aws_user_pools_web_client_id": "7gjaneam8eimsqufjcotrckh24",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wruwhrav6veyha5cuxcun7ualq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "safariphotobucket-master",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "photo-albums-20190727031947-hostingbucket-master",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://photo-albums-20190727031947-hostingbucket-master.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
